# Based on https://github.com/gruvbox-community/gruvbox

export GV_BLACK_0H=0xff1d2021
export GV_BLACK_0=0xff282828
export GV_WHITE=0xfffbf1c7
export GV_GREY=0xfffa89984
export GV_AQUA=0xff689d6a
export GV_YELLOW=0xffd79921
export GV_ORANGE=0xffd65d0e
export GV_RED=0xffcc241d

export GV_BAR_COLOR=$GV_BLACK_0H
export GV_BAR_BORDER_COLOR=$GV_AQUA

export GV_POPUP_BACKGROUND_COLOR=$GV_BLACK_0
export GV_POPUP_BORDER_COLOR=$GV_WHITE

export GV_BACKGROUND_1=$GV_BLACK_0
export GV_BACKGROUND_2=$GV_GREY

export GV_ICON_COLOR=$GV_WHITE # Color of all icons
export GV_ICON_HIGHLIGHT_COLOR=$GV_WHITE
export GV_LABEL_COLOR=$GV_WHITE # Color of all labels
export GV_LABEL_HIGHLIGHT_COLOR=$GV_WHITE

export GV_YABAI_SPACE_LABEL_COLOR=$GV_GREY
export GV_YABAI_SPACE_BACKGROUND_COLOR=$GV_BLACK_0
export GV_YABAI_SPACE_BACKGROUND_BORDER_COLOR=$GV_GREY
export GV_YABAI_SPACE_BACKGROUND_BORDER_COLOR_ACTIVE=$GV_AQUA

export GV_BATTERY_MEDIUM=$GV_ORANGE
export GV_BATTERY_LOW=$GV_RED
