general.import = ["~/.config/alacritty/themes/themes/zenburn.toml"]
general.live_config_reload = true

[font]
size = 12.0

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Liga SFMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
# decorations = "full"
startup_mode = "SimpleFullscreen"
dynamic_padding = true
dynamic_title = false
opacity = 0.95

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 200
lines = 60
