theme = "gruvbox_community"

[editor.indent-guides]
render = true
character = "┆"

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "diagnostics", "file-name"]
right = ["position-percentage", "spacer"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
