#!/bin/bash

source "$CONFIG_DIR/themes/gruvbox.sh"

# Color Palette
export BLACK=0xff181926
export WHITE=0xffcad3f5
export RED=0xffed8796
export GREEN=0xffa6da95
export BLUE=0xff8aadf4
export YELLOW=0xffeed49f
export ORANGE=0xfff5a97f
export MAGENTA=0xffc6a0f6
export GREY=0xff939ab7
export TRANSPARENT=0x00000000

# General bar colors
export BAR_COLOR=$GV_BAR_COLOR
export BAR_BORDER_COLOR=$GV_BAR_BORDER_COLOR

export ICON_COLOR=$GV_ICON_COLOR # Color of all icons
export ICON_HIGHLIGHT_COLOR=$GV_ICON_HIGHLIGHT_COLOR
export LABEL_COLOR=$GV_LABEL_COLOR # Color of all labels
export LABEL_HIGHLIGHT_COLOR=$GV_LABEL_HIGHLIGHT_COLOR # Color of all labels

export YABAI_SPACE_LABEL_COLOR=$GV_YABAI_SPACE_LABEL_COLOR
export YABAI_SPACE_ICON_COLOR=$GV_YABAI_SPACE_ICON_COLOR
export YABAI_SPACE_BACKGROUND_COLOR=$GV_YABAI_SPACE_BACKGROUND_COLOR
export YABAI_SPACE_BACKGROUND_BORDER_COLOR=$GV_YABAI_SPACE_BACKGROUND_BORDER_COLOR
export YABAI_SPACE_BACKGROUND_SELECTED_COLOR=$GV_YABAI_SPACE_BACKGROUND_SELECTED_COLOR
export YABAI_SPACE_BACKGROUND_BORDER_COLOR_ACTIVE=$GV_YABAI_SPACE_BACKGROUND_BORDER_COLOR_ACTIVE

export POPUP_BACKGROUND_COLOR=$GV_POPUP_BACKGROUND_COLOR
export POPUP_BORDER_COLOR=$GV_POPUP_BORDER_COLOR

export BATTERY_MEDIUM=$GV_BATTERY_MEDIUM
export BATTERY_LOW=$GV_BATTERY_LOW
export BATTERY_SUPERLOW=$GV_BATTERY_SUPERLOW
export CHARGER_CONNECTED=$GV_CHARGER_CONNECTED
