#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# global settings
yabai -m config \
    external_bar all:0:36                    \
    mouse_follows_focus          off         \
    focus_follows_mouse          off         \
                                             \
    window_placement             first_child \
    window_topmost               off         \
    window_shadow                off         \
    window_opacity               on          \
    window_opacity_duration      0.0         \
    active_window_opacity        0.97        \
    normal_window_opacity        0.97        \
    window_border                on          \
    window_border_width          2           \
    active_window_border_color   0xff689d6a  \
    normal_window_border_color   0xffa89984  \
    window_border_radius         0           \
    insert_feedback_color        0xff61afef  \
    split_ratio                  0.50        \
    auto_balance                 off         \
                                             \
    mouse_modifier               fn          \
    mouse_action1                move        \
    mouse_action2                resize      \
    mouse_drop_action            swap        \
                                             \
    layout                       bsp         \
    top_padding                  0           \
    bottom_padding               0           \
    left_padding                 0           \
    right_padding                0           \
    window_gap                   1           \

yabai -m space 1 --label 1
yabai -m space 2 --label 2
yabai -m space 3 --label 3
yabai -m space 4 --label 4
yabai -m space 5 --label 5
yabai -m space 6 --label 6
yabai -m space 7 --label 7

yabai -m rule --add app="Alacritty" space=2
yabai -m rule --add app="Firefox" space=3
yabai -m rule --add app="Slack" space=4
yabai -m rule --add app="Telegram" space=7

yabai -m config 
# Refocus when window is closed
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"


echo "yabai configuration loaded.."
